language: php

php: "7.2"

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

env:
  - TEST_TAGS=lightning PROFILE_NAME=lightning
  - TEST_TAGS=~search PROFILE_NAME=lightning_extender

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add .travis-ci/travis.php.ini
  - phpenv rehash

  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # Add dev dependencies that shouldn't be shipped to implementors and build the
  # Lightning code base.
  - composer require --dev vaimo/binary-chromedriver drupal/drupal-extension:^3.4 drupal/media_entity_generic:^1.0 --no-update
  - composer install

  # Install Lightning.
  - drush site:install lightning --yes --db-url sqlite://db.sqlite
  # Reinstall Lightning if we want to run tests on a sub-profile.
  - if [ $PROFILE_NAME != 'lightning' ]; then drush site:install $PROFILE_NAME --yes --db-url sqlite://db.sqlite; fi

  # Update code base to HEAD.
  - composer nuke
  - composer require acquia/lightning:dev-8.x-4.x --no-update
  - composer update
  - ln -s docroot/profiles/contrib/lightning/tests/lightning_extender docroot/profiles/contrib/lightning_extender

  # Run database and Lightning config updates.
  - drush updatedb --yes
  - drush update:lightning --no-interaction
  - drush cache-rebuild
  - drush pm-uninstall --yes history

before_script:
  - drush runserver --default-server=builtin --quiet 8080 &
  - chromedriver --port=4444 &

script:
  - behat --strict --tags=${TEST_TAGS}

matrix:
  fast_finish: true
